import { users } from "/js/utils/source/users/users.js";

const userLookup = Object.fromEntries(users.map((user) => [user.id, user]));

export const posts = [
  {
    id: "1",
    imgSrc: "/resources/images/rayul-_M6gy9oHgII-unsplash.webp",
    imgAlt: "rayul-_M6gy9oHgII-unsplash",
    title: "Travel for food in 2025",
    caption: "When food meets plate, pizza is my date.",
    text: "Post text content will be added in this field later.",
    likes: "",
    username: userLookup[1].username,
    userId: 1,
    comments: [
      {
        id: "c1",
        text: "Looks amazing!",
        likes: 2,
        username: "alice",
        userId: 2,
      },
      {
        id: "c2",
        text: "I want to visit!",
        likes: 3,
        username: "bob",
        userId: 3,
      },
    ],
  },
  {
    id: "2",
    title: "The Ultimate Burger Experience",
    imgSrc: "/resources/images/chad-montano--GFCYhoRe48-unsplash.jpg",
    imgAlt: "chad-montano--GFCYhoRe48-unsplash",
    caption: "Juicy, cheesy, and absolutely delicious!",
    text: "From classic cheeseburgers to gourmet creations, the world of burgers is as diverse as it is mouthwatering.",
    likes: "",
    username: userLookup[1].username,
    userId: 1,
    comments: [
      {
        id: "c3",
        text: "This is mouthwatering!",
        likes: 5,
        username: "charlie",
        userId: 4,
      },
    ],
  },
  {
    id: "3",
    title: "Savoring the Best Ramen Bowls",
    imgSrc: "/resources/images/casey-lee-awj7sRviVXo-unsplash.jpg",
    imgAlt: "casey-lee-awj7sRviVXo-unsplash",
    caption: "A warm hug in a bowl of noodles and broth.",
    text: "Whether it's tonkotsu, miso, or shoyu, ramen is the ultimate comfort food that brings people together.",
    likes: "",
    username: userLookup[3].username,
    userId: 3,
    comments: [],
  },
  {
    id: "4",
    title: "The Art of Baking Perfection",
    imgSrc: "/resources/images/brooke-lark-1Rm9GLHV0UA-unsplash.jpg",
    imgAlt: "brooke-lark-1Rm9GLHV0UA-unsplash",
    caption: "Sweet treats that melt in your mouth!",
    text: "From croissants to cupcakes, the world of baking is filled with endless possibilities for delightful indulgence.",
    likes: "",
    username: userLookup[4].username,
    userId: 4,
    comments: [],
  },
  {
    id: "5",
    title: "Exotic Fruits You Must Try",
    imgSrc: "/resources/images/anh-nguyen-kcA-c3f_3FE-unsplash.jpg",
    imgAlt: "anh-nguyen-kcA-c3f_3FE-unsplash",
    caption: "Nature's sweetest gifts in vibrant colors.",
    text: "From dragon fruit to mangosteen, these exotic fruits are as delicious as they are beautiful.",
    likes: "",
    username: userLookup[5].username,
    userId: 5,
    comments: [],
  },
  {
    id: "6",
    title: "Old Fashioned Happiness",
    imgSrc: "/resources/images/adam-jaime-dmkmrNptMpw-unsplash.jpg",
    imgAlt: "adam-jaime-dmkmrNptMpw-unsplash",
    caption: "Bitter, spice and everything nice!",
    text: "A traditional experience enhanced with citrus and cinnamon.",
    likes: "",
    username: userLookup[6].username,
    userId: 6,
    comments: [],
  },
];
