export const users = [
  {
    id: "1",
    username: "JimmyCraig",
    name: "Jimmy Craig",
    email: "j.craig@email.com",
    password: "",
    description: "Born in Rome, travelling for food.",
    avatarSrc: "/resources/images/rayul-_M6gy9oHgII-unsplash.webp",
    avatarAlt: "rayul-_M6gy9oHgII-unsplash",
    followers: "201",
    following: "34",
    posts: {
      numberOf: "29",
    },
  },
  {
    id: "2",
    username: "JaneDoe95",
    name: "Jane Doe",
    email: "janey@doe.com",
    password: "",
    description: "Fruitarian conquering the world!",
    avatarSrc: "/resources/images/chad-montano--GFCYhoRe48-unsplash.jpg",
    avatarAlt: "chad-montano--GFCYhoRe48-unsplash",
    followers: "44",
    following: "2130",
    posts: {
      numberOf: "3",
    },
  },
  {
    id: "3",
    username: "ChrisGoesWhereFoodIs",
    name: "Chris Isaak Johnson",
    email: "",
    password: "",
    description: "x-rated food enthusiast.",
    avatarSrc: "/resources/images/casey-lee-awj7sRviVXo-unsplash.jpg",
    avatarAlt: "casey-lee-awj7sRviVXo-unsplash",
    followers: "",
    following: "",
    posts: {
      numberOf: "",
    },
  },
  {
    id: "4",
    username: "BakingWithEmily",
    name: "Emily Suarez",
    email: "",
    password: "",
    description: "A sweet treats girl from all over the world!",
    avatarSrc: "/resources/images/brooke-lark-1Rm9GLHV0UA-unsplash.jpg",
    avatarAlt: "brooke-lark-1Rm9GLHV0UA-unsplash",
    followers: "",
    following: "",
    posts: {
      numberOf: "",
    },
  },
  {
    id: "5",
    username: "Fusion_John",
    name: "Johnas Casterion",
    email: "",
    password: "",
    description: "Colorful boy from South of the Equator.",
    avatarSrc: "/resources/images/anh-nguyen-kcA-c3f_3FE-unsplash.jpg",
    avatarAlt: "anh-nguyen-kcA-c3f_3FE-unsplash",
    followers: "",
    following: "",
    posts: {
      numberOf: "",
    },
  },
  {
    id: "6",
    username: "Lazy_with_Liam",
    name: "Liam Haze Jansen",
    email: "",
    password: "",
    description: "Just ease into it and keep eating!",
    avatarSrc: "/resources/images/adam-jaime-dmkmrNptMpw-unsplash.jpg",
    avatarAlt: "adam-jaime-dmkmrNptMpw-unsplash",
    followers: "",
    following: "",
    posts: {
      numberOf: "",
    },
  },
];
